@startuml
package data #FF00FF {
  package raw_imagery #LightSkyBlue {
      package flights #CCCCEE { 
        class jpeg
        class raw
      }
      package flights_logs #CCCCEE { 
        class gpx
        class csv
      }
    }
  package rasters #LightGreen {
      package elevation {
        class tiff
    }
      package spectral #CCCCEE {
        class cog-tiff
        class hdf5
    }
  }
  package pointclouds #CCCCEE {
      package compressed {
        class laz
    }
      package entwine {
        class ept
    }
  }
}
@enduml